export const GETAPI ="GETAPI"
export const PROJECTAPI="PROJECTAPI"
export const ALBUM="ALBUM"
export const RECENTACTIVITIES="RECENTACTIVITIES"
export const GETPRODETAIL="GETPRODETAIL"
export const CHANGEPASSWORD = 'CHANGEPASSWORD'
